config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'about' => 'homes#about', as: 'about'

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres
    resources :items
    resources :customers
    resources :orders
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy

  def customer_full_name
    last_name + " " + first_name
  end

  def aaa
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details

  def tax_include
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }

  SHIPPING = 800

  def get_total_price
    sum = 0
    OrderDetail.where(order_id: id).each do |order_detail|
      sum += order_detail.subtotal
    end
    return sum
  end

  def get_billing_amount
    get_total_price + SHIPPING
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def item_name
    Item.find(item_id).name
  end

  def tax_include_price
    (price * 1.1).floor
  end

  def subtotal
    tax_include_price * amount
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(
      :last_name, 
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :email,
      :postal_code,
      :address,
      :telephone_number,
      :is_active
      )
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    @customer = Customer.find(@order.customer_id)
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order('created_at DESC').limit(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h4><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h4>
<%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
  <h4>会員ID</h4>  
  <%= @customer.id %>
  <h4>氏名</h4>
  <%= f.text_field :last_name %> <%= f.text_field :first_name %> 
  <h4>フリガナ</h4>
  <%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %>
  <h4>郵便番号</h4>
  <%= f.text_field :postal_code %>
  <h4>住所</h4>
  <%= f.text_field :address %>
  <h4>電話番号</h4>
  <%= f.text_field :telephone_number %>
  <h4>メールアドレス</h4>
  <%= f.text_field :email %>
  <h4>会員ステータス</h4>
  <%= f.radio_button :is_active, 'true' %>
  <%= f.label :is_active, '有効', value: true %>
  <%= f.radio_button :is_active, 'false' %>
  <%= f.label :is_active, '退会', value: false %>
  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/admin/customers/index.html.erb
<table>
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>    
  </tr>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      
      <td>
        <%= link_to admin_customer_path(customer) do %>
          <%= customer.last_name %><%= customer.first_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_active %>
          有効
        <% else %>
          退会
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/customers/show.html.erb
<h4>会員ID</h4>
<%= @customer.id %>
<h4>氏名</h4>
<%= @customer.last_name %> <%= @customer.first_name %>
<h4>フリガナ</h4>
<%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
<h4>郵便番号</h4>
<%= @customer.postal_code %>
<h4>住所</h4>
<%= @customer.address %>
<h4>電話番号</h4>
<%= @customer.telephone_number %>
<h4>メールアドレス</h4>
<%= @customer.email %>
<h4>会員ステータス</h4>
<% if @customer.is_active %>
  有効
<% else %>
  退会
<% end %>
<%= link_to '編集する', edit_admin_customer_path(@customer) %>

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>

<%= form_with model: @genre, url: admin_genre_path(@genre), submit: '更新' do |f| %>
  <%= f.label :name, "ジャンル名" %>
  <%= f.text_field :name %>
	<%= f.submit '更新', class: "btn btn-primary ml2" %>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル追加・一覧</h2>

<%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
  <div class="form-group">
    <label for="genre_name">ジャンル名</label>
    <%= f.text_field :name, class: 'form-control genre_name' %>
  </div>
  <%= f.submit '新規登録' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th></th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tr>
    <td>
      <%= genre.name %>
    </td>
    <td>
      <%= link_to "編集", edit_admin_genre_path(genre) %>
    </td>
  </tr>
  <% end %>  
</table>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
  <h4>商品画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_area :introduction %>
  <h4>税抜き価格</h4>
  <%= f.text_field :price %>
  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<table>
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜き価格</th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= link_to item.name, admin_item_path(item) %></td>
    <td><%= item.price %></td>
  </tr>
  <% end %>
</table>

app/views/admin/items/new.html.erb
<%= form_with model: @item, url: admin_items_path do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_area :introduction %>
  <h4>税抜き価格</h4>
  <%= f.text_field :price %>
  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h4>商品画像</h4>
<% if @item.image.attached? %>
  <%= image_tag @item.image, size:"200x200" %>
<% else %>
  <%= image_tag 'no_image', size: "200x200" %>
<% end %>
<h4>商品名</h4>
<%= @item.name %>
<h4>商品紹介</h4>  
<%= @item.introduction %>
<h4>税込価格(税抜価格)</h4>
<%= "#{@item.tax_include.to_s(:delimited)} (#{@item.price.to_s(:delimited)}) 円" %>
<%= link_to '商品編集', edit_admin_item_path(@item) %>

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>
<table>
  <tr>
    <th>購入日時</th>
    <th>購入者</th>
    <th>注文個数</th>
  </tr>
  <% @orders.each do |order| %>
  <tr>
    <td><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
    <td><%= order.customer.customer_full_name %></td>
    <td><%= order.order_details.sum(:amount) %></td>
  </tr>
  <% end %>
</table>

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>
<table>
  <tr>
    <td>購入者</td>
    <td><%= @customer.customer_full_name %></td>
  </tr>
  <tr>
    <td>注文日</td>
    <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
  </tr>
  <tr>
    <td>配送先</td>
    <td>
      〒<%= @customer.postal_code %>
      <%= @customer.address %></br>
      <%= @customer.customer_full_name %>
    </td>
  </tr>
  <tr>
    <td>支払方法</td>
    <td><%= @order.payment_method_i18n %></td>
  </tr>
</table>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item_name %></td>
      <td><%= order_detail.tax_include_price %></td>
      <td><%= order_detail.amount %></td>
      <td><%= order_detail.subtotal %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<h4>商品合計</h4>
<%= @order.get_total_price %>
<h4>送料</h4>
<%= Order::SHIPPING %>
<h4>請求金額合計</h4>
<%= @order.get_billing_amount %>